Experiment_name: joint_27_2_finetune_test

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/sign/27_2/train_val_data_joint.npy
  label_path: ./data/sign/27_2/train_val_labels.pkl
  debug: False
  random_choose: True
  window_size: 100
  random_shift: True
  normalization: True
  random_mirror: True
  random_mirror_p: 0.5
  is_vector: False

test_feeder_args:
  data_path: ./data/sign/27_2/test_data_joint.npy
  label_path: ./data/sign/27_2/test_labels_pseudo.pkl
  random_mirror: False
  normalization: True
  debug: False

# model
model: model.decouple_gcn_attn.Model
model_args:
  num_class: 226
  num_point: 27
  num_person: 1
  graph: graph.sign_27.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.01
step: [50]

# training
device: [0,1]
phase: test
weights: final_models/27_2_finetuned/joint_finetuned.pt
keep_rate: 0.9
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
num_epoch: 100
nesterov: True
warm_up_epoch: 0