Experiment_name: sign_joint_motion_final

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/sign/27_2/train_data_joint_motion.npy
  label_path: ./data/sign/27_2/train_label.pkl
  debug: False
  random_choose: True
  random_shift: True
  window_size: 100
  random_mirror: True
  random_mirror_p: 0.5
  normalization: True
  is_vector: True

test_feeder_args:
  data_path: ./data/sign/27_2/val_data_joint_motion.npy
  label_path: ./data/sign/27_2/val_gt.pkl
  random_mirror: False
  normalization: True
  is_vector: True

# model
model: model.decouple_gcn_attn.Model
model_args:
  num_class: 226
  num_point: 27
  num_person: 1
  graph: graph.sign_27.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [150, 200]

# training
device: [0,1,2,3]
keep_rate: 0.9
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
num_epoch: 250
nesterov: True
warm_up_epoch: 20