Experiment_name: sign_joint_final

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/sign/1/train_data_joint.npy
  label_path: ./data/sign/1/train_label.pkl
  meaning_path: ./data/sign/1/meaning.pkl
  debug: False
  random_choose: True
  window_size: 100
  random_shift: True
  normalization: True
  random_mirror: True
  random_mirror_p: 0.5
  is_vector: False

test_feeder_args:
  data_path: ./data/sign/1/val_data_joint.npy
  label_path: ./data/sign/1/val_label.pkl
  meaning_path: ./data/sign/1/meaning.pkl
  random_mirror: False
  normalization: True

# model
# 226 (num classes)
model: model.decouple_gcn_attn.Model
model_args:
  num_class: 28 #53 110 # AEC=28, PUCP=36 , WLASL=101
  num_point: 71
  num_person: 1
  graph: graph.sign_27.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [150, 200]

# training
device: [0, 1]
keep_rate: 0.9
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
num_epoch: 250
nesterov: True
warm_up_epoch: 20
